baseURL = "https://diary.oino.li"
title = "Diary"
languageCode = "ja-JP"
theme = "hugo-journal"
ignoreErrors = ["error-remote-getjson"]
[params]
  description = "Diary"
  tagline = "You're always haunted by the idea you're wasting your life"
  mainSections = ["post", "media"]
  customCSS = ["/css/amazon.css"]
  amazonJpAffiliate = "kinak0pypy02-22"
  twitterCard = "/media/icon.jpeg"
[author]
  name = "dangorogoro"